<button class="cliqueModifArticle lienbutton">Modifier le sujet</button>

<form method="POST" action="" class="modifArticle notvisibleart">
			<div class="titrenewsujetforum">
				<input name="sujet" type="text" class="titresujet" value="<?=$sujet?>"placeholder="Sujet" required>
			</div>
			<div class="clearfix"></div>

			<div class="wrapper-mce clearfix">
				<textarea name="description" class="mce" ><?=$description?></textarea>
			</div>
			<input type="hidden" value="modifSujet" name="action">
			<button class="creerSujet" type="submit">MODIFIER SUJET</button>
		</form>