<div class="sujetforum">
	<a href="index.php?page=forum" class="returnForumSujet">Retourner au forum</a> 
		<div class="entete">
			<p class="col-md-2">Auteur</p>
			<p class="col-md-7"><?=$sujet?></p>
			<p class="col-md-3 dateSujet"><?=$date?></p>
	</div>
	<div class="textesujetforum">
			<?=$description?>
	</div>
	<div class="commentaires">
		<?php require('apps/forum-commentaires.php') ?>
	</div>
	<button class="buttonReponseCommentaire" type="submit">Répondre</button>
	<div class="reponse-forum">
		<form action="index.php?page=forum-reponse" method="POST">
			<div class="clearfix"></div>
			<div class="wrapper-mce clearfix">
				<textarea name="description" class="mce" ></textarea>
			</div>
			<button class="repondre" type="submit">Répondre</button>
			<input type="hidden" value="<?= $sujetid; ?>" name="id_forum">
		</form>
	</div>
		</form>
	</div>
</div>