<div class="header">
	<h1>DreamTeam 1</h1>
	<nav class="nav_top clearfix">
		<div class="row">
			<div class="col-md-8 col-sm-6">
				<ul>
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href="index.php?page=article">News</a></li>
					<li><a href="index.php?page=apropos">A propos</a></li>
					<li><a href="index.php?page=forum">Forum</a></li>
					<li><a href="index.php?page=contact">Contacts</a></li>
				</ul>
			</div>
			<div class="col-md-4 col-sm-6 login">
				<?php 
					require('apps/header-log.php');
				 ?>
			</div>
		</div>
	</nav>
	<?php require('apps/inscription.php') ?>
	<form action="index.php?page=login" method="POST" class="log">
		<div class="fermer"> X </div>
		<p>Se connecter</p>
		<label for="pseudo">Nom ou E-mail :</label>
		<input id="pseudo" type="text" name="user" required>
		<label for="mdp" >Mot de passe :</label>
		<input type="password" id="mdp" name="pass" required>
		<a href="">[ mot de passe oublié ? ]</a>
		<button>Connexion</button>
	</form>
	<?php require('apps/add-article.php'); ?>
</div>