	<div class="wrapper-caroussel">
		<ul class="caroussel">
			<li><img src="./views/images/slider/slider1.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider2.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider3.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider4.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider5.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider6.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider7.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider8.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider9.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider10.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider11.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider12.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider13.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider14.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider15.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider16.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider17.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider18.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider19.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider20.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider21.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider22.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider23.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider24.jpg" alt=""></li>
			<li><img src="./views/images/slider/slider25.jpg" alt=""></li>
		</ul>
	</div>

	<div class="row last-news">
		<h2>Derniers Articles</h2>
		<?php require('apps/home-article.php'); ?>
	</div>