<div class="wrapperldo">
	<div class="wrapperldotxt">
		<h2>Livre d'or</h2>


		<form action="" method="post">
			<div class="formldo">
				<label><span class="spanldo">Nom :</span><input type="text" placeholder="votre nom" name="nom"></label>
			</div>

			<div class="formldo">
				<label><span class="spanldo">Titre :</span>
					<input type="text" placeholder="Titre" name="titre">
				</label>
			</div>

			<div class="formldo">
				<label><span class="spanldo">Votre commentaire :</span><textarea name="description" placeholder="votre commentaire max 300 caractères" maxlength="300"></textarea></label>
			</div>
			<div class="boutonldo">
				<input type="submit" value="Send">
			</div>
		</form>

		<section class="sectionldo">
			<article>
				<?php require('apps/livredor-single.php') ?>
			</article>
			
		</section>
	</div>		
</div>
