<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">

	    <title>Dreamteam - apprendre le travail collaboratif par Git</title>
	    <link rel="stylesheet" href="views/styles/reset.css">
	    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="views/styles/jquery.bxslider.css">
	    <link rel="stylesheet" href="views/styles/bootstrap.min.css">
	    <link rel="stylesheet" href="views/styles/style.css">
	    <link rel="stylesheet" type="text/css" href="views/styles/flaticon.css"> 
	    <script type="text/javascript" src="apps/scripts/bootstrap.min.js"></script>
	    <script type="text/javascript" src="apps/scripts/script.js"></script>
	</head>
	<body>
		<header>
			<div class="container main">
				<?php require('apps/header.php'); ?>
			</div>
		</header>
		<div class="container main">
			<section>
				<?php require('apps/content.php'); ?>
			</section>
		</div>
		<div class="tchat">
			<div class="tchat-wd">
				<div class="tchat-content">
					<?php require('apps/tchat.php'); ?>
				</div>
				<form method="POST" class="tchat-form" action="apps/tchat-form.php">
					<textarea name="tchat" placeholder="votre message" fixed></textarea>

				</form>	
			</div>
			<h3>Tchat Room</h3>		
		</div>
		<footer>
			<div class="container main">
				<?php require('apps/footer.php'); ?>
			</div>
		</footer>
		<script type="text/javascript" src="./views/tinymce/tinymce.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){ /*Que l'on peut résumer par : $(function(){ */
				tinymce.init({
				    selector: "textarea.mce"
				 });
				});
		</script>
			<!-- jQuery library (served from Google) -->
		<script type="text/javascript" src="apps/scripts/jquery.bxslider.min.js"></script>
		<script>
			$(document).ready(function(){ /*Que l'on peut résumer par : $(function(){ */
				$('.caroussel').bxSlider({
					mode: "fade"
					// startSlide
				});
			});
		</script>
	</body>
</html>