<div class="tchat">
	<div class="tchat-wd">
		<div class="tchat-content" id="tchat-content">
			<?php //require('apps/tchat-liste.php'); ?>
		</div>
		<form id="tchat" method="POST" action="index.php?ajax=tchat-form">
				<input name="message" id="tchat_message" placeholder="votre message">
				<input type="hidden" value="<?= $_SESSION['id']; ?>" name="id_user" id="id_user">
		</form>	
	</div>
	<h3>Tchat Room</h3>		
</div>



