
	<form method="POST" action="index.php?page=formarticle" class="notvisibleart article">
		<div class="fermer"> X </div>
		<p>Création d'un article</p>
		<label for="date">Date :</label>
		<input id="date" name="date" type="date" placeholder="JJ/MM/AAAA">
		<label for="title">Titre :</label>
		<input id="title" name="title" type="text" placeholder="Entrez votre titre">
		<label for="description">Description :</label>
		<textarea id="description" name="description" rows="4" cols="50" placeholder="Entrez votre description"></textarea>
		<label for="priority">Source :</label>
		<input id="priority" name="priority" type="text" placeholder="La source/lien">
		<button type="submit">ENVOYER</button>
	</form>