
	<div class="container">
	<form method="POST" action="../apps/formarticle.php">
		<div class="alaligne">
		<label for="date">Date :</label>
			<input id="date" name="date" type="date" placeholder="JJ/MM/AAAA">
		</div>
		<div class="alaligne">
		<label for="title">Titre :</label>
			<input id="title" name="title" type="text" placeholder="Entrez votre titre">
		</div>
		<div class="alaligne">
		<label for="description">Description :</label>
			<textarea id="description" name="description" rows="4" cols="50" placeholder="Entrez votre description"></textarea>
		</div>
		<div class="alaligne">
		<label for="priority">Source :</label>
			<input id="priority" name="priority" type="text" placeholder="La source/lien">
		</div>
		<div class="alaligne">
			<button type="submit">ENVOYER</button>
		</div>
	</form>
	</div>