<div class="content">
	<div class="apropos">
		<p>Nous sommes la 3eme promos de la 3WA est surement la meilleure de toutes !! </p>
		<p>La team se compose de 5 membres et un remplacant !! On va commmencer par notre leader et l'ancêtre de toutes choses sur terre. : </p>
		<p>Le doyen : notre designer par excellence.</p>
		<p>les codeurs fou : Alex et mika !!!</p>
		<p>les n(b)oobs : La paire Laurent et Steve!!!</p>
		<p>le remplacant notre prof !!! Qui est la pour rectifier le tir des erreurs de tous.</p>
		<p>La DreamTeam est la pour régler tout vos problèmes et en faire de nouveaux rien que pour vous. Pour se faire de l'argent toutes les methodes  sont bonnes.</p>
	</div>
</div>
