<div class="contacter">
	<h2>Nous contacter</h2>

	<p>Vous avez une question ? Vous souhaitez obtenir des informations</p>
	<p>Un problème sur votre site, ecommerce, forum ou tout autre admnistration?</p>
	<p>Vous pouvez nous joindre par :</p>
	<p><i class="flaticon-cellphone67"></i>Téléphone au 03 80085 55</p>
	<p><i class="flaticon-email23"></i>Mail au DreamTeam@gmail.com</p>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2639.219964896662!2d7.741729999999998!3d48.58648700000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796c84ed7c1b1d9%3A0xa3c93a25f60c1c4b!2sPlace+des+Halles!5e0!3m2!1sfr!2sfr!4v1431698508827" class="googlemap" ></iframe>
</div>