<div class="footer">
	<div class="row">
		<div class="col-md-5 tac">
	<?php
		require('views/livredorfooter.phtml');
	?>

		</div>
		<div class="col-md-2">
			<nav>
				<ul>
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href="index.php?page=article">News</a></li>
					<li><a href="index.php?page=apropos">A propos</a></li>
					<li><a href="index.php?page=forum">Forum</a></li>
					<li><a href="index.php?page=contact">Contacts</a></li>
				</ul>
			</nav>
		</div>
		<div class="col-md-5">
			<i class="flaticon-facebook29"></i>
			<i class="flaticon-linkedin12"></i>
			<i class="flaticon-photos12"></i>
			<i class="flaticon-twitter2"></i>
		</div>
	</div>
</div>