<div class="footer">
	<div class="row">
		<div class="col-md-6 tac">
	<?php
		require('views/livredorfooter.phtml');
	?>

		</div>
		<div class="col-md-6">

			<nav>
				<ul>
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href="index.php?page=article">Articles</a></li>
					<li><a href="index.php?page=about">A propos</a></li>
					<li><a href="index.php?page=news">News</a></li>
					<li><a href="index.php?page=forum">Forum</a></li>
					<li><a href="index.php?page=contact">Contacts</a></li>
				</ul>
			</nav>
		</div>
	</div>
</div>