<div class="footer">
	<div class="row">
		<div class="col-md-5 tac">
			<?php require('apps/livredorfooter.php'); ?>

		</div>
		<div class="col-md-2">
			<nav>
				<ul>
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href="index.php?page=article">News</a></li>
					<li><a href="index.php?page=apropos">A propos</a></li>
					<li><a href="index.php?page=forum">Forum</a></li>
					<li><a href="index.php?page=contact">Contacts</a></li>
				</ul>
			</nav>
		</div>
		<div class="col-md-5 social">
			<a href="#"><i class="flaticon-facebook29"></i></a>
			<a href="#"><i class="flaticon-linkedin12"></i></a>
			<a href="#"><i class="flaticon-photos12"></i></a>
			<a href="#"><i class="flaticon-twitter2"></i></a>
		</div>
	</div>
</div>