<div class="sujetforum" id="sujetForum">
	<a href="index.php?page=forum" class="returnForumSujet">Retourner au forum</a> 
	<div class="sujet">
	<div class="entete">
		<p class="col-md-2"><a href="index.php?page=profil-user&id_user=<?=$id_user?>"><?=$user_pseudo?></a></p>
		<p class="col-md-7"><?=$sujet?></p>
		<p class="col-md-3 dateSujet"><?=$date?></p>
	</div>
	<div class="textesujetforum">
			<?=$description?>
	</div>
	</div>
	<div class="commentaires">
		<?php require('apps/forum-commentaires.php') ?>
	</div>
</div>