<div class="content">
	<div class="forum ">
	<nav class="navforum">
		<button class="newsujet col-md-3">Nouveau sujet</button>
		<span class="col-md-6">
		<input type="text" placeholder="Rechercher dans le forum">
		<select name="search" id="search">
          	 <option value="sujet">Sujet</option>
          	 <option value="auteur">Auteur</option>
      	 </select>
		<button>Chercher</button>
		</span>
		<button class="actualiserforum col-md-3">Actualiser</button>
	</nav>
		<div class="entete">
			<p class="col-md-6">Sujet</p>
			<p class="col-md-2">Auteur</p>
			<p class="col-md-2">Nombre commentaires</p>
			<p class="col-md-2">Dernière réponse</p>
		</div>
		<div class="pair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="impair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="pair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="impair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="pair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="impair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="pair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="impair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="pair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="impair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="pair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="impair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="pair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="impair">
			<a href="" class="col-md-6">Un sujet au hasard</a>
			<a href="" class="col-md-2">George</a>
			<p class="col-md-2">234</p>
			<p class="col-md-2">20h50</p>
		</div>
	</div>
	<div class="sujetforum">
	<button>Répondre</button>
	<button class="newsujet">Nouveau sujet</button>
	<button>Liste des sujets</button>
	<button>Actualiser</button>
		<div class="entete">
			<p class="col-md-2">Auteur</p>
			<p class="col-md-8">Un sujet au hasard</p>
			<p class="col-md-2">20h50</p>
		</div>
		<div class="textesujetforum">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti animi praesentium officia laboriosam qui voluptates nam fuga, quas sapiente atque, culpa corporis minima neque pariatur accusamus nisi dolor ipsum aliquam.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt quo fuga suscipit, amet repellat saepe. Error iure eaque natus aliquam nulla quos fuga quod unde distinctio, obcaecati, sit vero voluptatibus.</p>
			<p>Illo in voluptatibus totam dolores magni expedita impedit, accusamus non omnis dolorum rem debitis beatae nostrum eaque soluta et aspernatur quibusdam quaerat hic quisquam modi porro praesentium, tempora iusto atque.</p>
		</div>
	</div>
	<div class="newsujetforum">
		<button class="returnforum">Retourner sur le forum</button>
		<div class="titrenewsujetforum">
			<label for="titresujet">Sujet :</label>
			<input type="text" id="titresujet" placeholder="sujet">
		</div>
		<div class="descriptionnewsujetforum">
			<label for="message">Message :</label>
			<textarea id="message" placeholder="Écris ton message"></textarea>
		</div>
	</div>
</div>