<div class="header">
	<h1>DreamTeam 1</h1>
	<nav class="nav_top clearfix">
		<ul class="pull-left">
			<li><a href="index.php?page=home">Home</a></li>
			<li><a href="index.php?page=article">Articles</a></li>
			<li><a href="index.php?page=about">A propos</a></li>
			<li><a href="index.php?page=news">News</a></li>
			<li><a href="index.php?page=forum">Forum</a></li>
			<li><a href="index.php?page=contact">Contacts</a></li>
		</ul>
	<button class="signup lienbutton pull-right">Sign up</button>
	<button class="signin lienbutton pull-right">Sign in</button>
	</nav>

	<form action="" method="POST" class="notvisible inscr">
		<p>Create your personnal account</p>
		<label for="username">Username :</label>
		<input id="username" type="text">
		<label for="email">Email Adress :</label>
		<input id="email" type="text">
		<label for="mdp">Password :</label>
		<input id="mdp" type="text">
		<label for="mdpconf">Confirm your password :</label>
		<input id="mdpconf" type="text">
		<button>Create an account :</button>
	</form>
	<form action="" method="POST" class="notvisible log">
		<p>Sign in</p>
		<label for="pseudo">Username or Email :</label>
		<input id="pseudo" type="text">
		<label for="mdp">Password <a href="">(forgot password)</a> :</label>
		<input type="text" id="mdp">
		<button>Sign in</button>
	</form>
</div>