<div class="header">
	<h1>DreamTeam 1</h1>
	<nav class="nav_top clearfix">
		<div class="row">
			<div class="col-md-8">
				<ul>
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href="index.php?page=article">News</a></li>
					<li><a href="index.php?page=apropos">A propos</a></li>
					<li><a href="index.php?page=forum">Forum</a></li>
					<li><a href="index.php?page=contact">Contacts</a></li>
				</ul>
			</div>
			<div class="col-md-4">
				<button class="signup lienbutton">S'inscrire</button>
				<button class="signin lienbutton">Se connecter</button>
				<button class="newarticle lienbutton">Créer un article</button>
			</div>
		</div>
	</nav>

	<form action="" method="POST" class="inscr">
		<div class="fermer">X</div>
		<p>Creez votre espace personnel</p>
		<label for="username">Nom d'utilisateur :</label>
		<input id="username" type="text">
		<label for="email">Adresse email :</label>
		<input id="email" type="text">
		<label for="mdp">Mot de passe :</label>
		<input id="mdp" type="password">
		<label for="mdpconf">Confirmer le mot de passe :</label>
		<input id="mdpconf" type="password">
		<button>Creer un compte</button>
	</form>
	<form action="" method="POST" class="log">
		<div class="fermer"> X </div>
		<p>Se connecter</p>
		<label for="pseudo">Nom ou Email :</label>
		<input id="pseudo" type="text">
		<label for="mdp">Mot de passe <a href="">(mot de passe oublié)</a> :</label>
		<input type="password" id="mdp">
		<button>Connexion</button>
	</form>
	<?php require('apps/add-article.php'); ?>
</div>