
<div class="footerlod">
	<p>Laissez un commentaire dans notre<a href="index.php?page=livredor" class="livredorlien"> <span class="ldo">Livre d'or</span></a> </p>
</div>

<div class="preview">
	<h3>Excellent!!!!</h3>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur eaque perferendis mollitia numquam quae harum voluptatum veritatis magnam, dicta aspernatur quia delectus beatae! Eaque consequatur, expedita quidem nostrum dolor veniam!
	</p>
</div>

