<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">
	    <title>livredor</title>
	    <link rel="stylesheet" href="views/styles/reset.css">
	    <link rel="stylesheet" href="views/styles/bootstrap.min.css">
	    <link rel="stylesheet" href="styles/style.css">
	    <link href='http://fonts.googleapis.com/css?family=Tangerine:400,700' rel='stylesheet' type='text/css'>
	    <script type="text/javascript" src="apps/scripts/bootstrap.min.js"></script>
	</head>
	<body>
		<div class="wrapperldo">
			<div class="wrapperldotxt">
				<h1>Livre d'or</h1>


				<form action="get">
					<div class="formldo">
						<label><span class="spanldo">Nom :</span><input type="text" placeholder="votre nom"></label>
					</div>
					<div class="formldo">
						<label><span class="spanldo">Votre commentaire :</span><textarea name="message" placeholder="votre commentaire"></textarea></label>
					</div>
					<div class="boutonldo">
						<input type="submit" value="Send">
					</div>
				</form>

				<section class="sectionldo">
						<h2>Excellent!!!!</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur eaque perferendis mollitia numquam quae harum voluptatum veritatis magnam, dicta aspernatur quia delectus beatae! Eaque consequatur, expedita quidem nostrum dolor veniam!</p>
					</article>
					<article>
						<h2>Les meilleurs</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, numquam alias officiis minima eveniet aut quibusdam tempora quaerat inventore, suscipit laboriosam quia, iste aperiam, tenetur deserunt voluptatibus dignissimos nesciunt distinctio?</p>
					</article>
					<article>
						<h2>Best of the best</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo dicta veniam labore nam ea odio, excepturi hic quis culpa recusandae. Facilis laborum eveniet nihil eligendi unde. Non illo quidem, unde?</p>
					</article>
					<article>
						<h2>Dreamteam !!!</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero sapiente illo ratione earum numquam libero quas facere natus deleniti pariatur minus, nam dolore quos suscipit porro necessitatibus, quia maxime unde.</p>
					</article>
				</section>
			</div>		
		</div>
	</body>
	
</html>
