<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">
	    <title>PHP - Jour 2 - MVC</title>
	    <link rel="stylesheet" href="views/styles/reset.css">
	    <link rel="stylesheet" href="views/styles/bootstrap.min.css">
	    <link rel="stylesheet" href="styles/livredorfooter.css">
	    <link href='http://fonts.googleapis.com/css?family=Tangerine:400,700' rel='stylesheet' type='text/css'>
	    <script type="text/javascript" src="apps/scripts/bootstrap.min.js"></script>
	</head>
	<body>
			<div>
				<p>Laissez un commentaire dans notre<a href="#"> <span class="ldo">Livre d'or</span></a> </p>
				</div>
			<div class="preview">
				<h3>Excellent!!!!</h3>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur eaque perferendis mollitia numquam quae harum voluptatum veritatis magnam, dicta aspernatur quia delectus beatae! Eaque consequatur, expedita quidem nostrum dolor veniam!
				</p>
			</div>




	</body>
	
</html>
