		<div class="wrapperldo">
			<div class="wrapperldotxt">
				<h2>Livre d'or</h2>


				<form action="get">
					<div class="formldo">
						<label><span class="spanldo">Nom :</span><input type="text" placeholder="votre nom"></label>
					</div>
					<div class="formldo">
						<label><span class="spanldo">Votre commentaire :</span><textarea name="message" placeholder="votre commentaire"></textarea></label>
					</div>
					<div class="boutonldo">
						<input type="submit" value="Send">
					</div>
				</form>

				<section class="sectionldo">
						<h3>Excellent!!!!</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur eaque perferendis mollitia numquam quae harum voluptatum veritatis magnam, dicta aspernatur quia delectus beatae! Eaque consequatur, expedita quidem nostrum dolor veniam!</p>
					</article>
					<article>
						<h3>Les meilleurs</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, numquam alias officiis minima eveniet aut quibusdam tempora quaerat inventore, suscipit laboriosam quia, iste aperiam, tenetur deserunt voluptatibus dignissimos nesciunt distinctio?</p>
					</article>
					<article>
						<h3>Best of the best</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo dicta veniam labore nam ea odio, excepturi hic quis culpa recusandae. Facilis laborum eveniet nihil eligendi unde. Non illo quidem, unde?</p>
					</article>
					<article>
						<h3>Dreamteam !!!</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero sapiente illo ratione earum numquam libero quas facere natus deleniti pariatur minus, nam dolore quos suscipit porro necessitatibus, quia maxime unde.</p>
					</article>
				</section>
			</div>		
		</div>
