<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">

	    <title>Dreamteam - apprendre le travail collaboratif par Git</title>
	    <link rel="stylesheet" href="views/styles/reset.css">
	    <link rel="stylesheet" href="views/styles/bootstrap.min.css">
	    <link rel="stylesheet" href="views/styles/style.css">
	    <script type="text/javascript" src="apps/scripts/bootstrap.min.js"></script>
	</head>
	<body>
		<header>
			<div class="container">
				<?php require('apps/header.php'); ?>
			</div>
		</header>
		<div class="container">
			<section>
				<?php require('apps/content.php'); ?>
			</section>
		</div>
		<footer>
			<div class="container">
				<?php require('apps/footer.php'); ?>
			</div>
		</footer>
	</body>
</html>