<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">

	    <title>Dreamteam - apprendre le travail collaboratif par Git</title>
	    <link rel="stylesheet" href="views/styles/reset.css">
		<link rel="stylesheet" type="text/css" href="views/styles/jquery.bxslider.css">
	    <link rel="stylesheet" href="views/styles/bootstrap.min.css">
	    <link rel="stylesheet" href="views/styles/style.css">
	    <script type="text/javascript" src="apps/scripts/bootstrap.min.js"></script>
	    <script type="text/javascript" src="apps/scripts/script.js"></script>
	</head>
	<body>
		<header>
			<div class="container">
				<?php require('apps/header.php'); ?>
			</div>
		</header>
		<div class="container">
			<section>
				<?php require('apps/content.php'); ?>
			</section>
		</div>
		<footer>
			<div class="container">
				<?php require('apps/footer.php'); ?>
			</div>
		</footer>
			<!-- jQuery library (served from Google) -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript" src="apps/scripts/jquery.bxslider.min.js"></script>
		<script>
			$(document).ready(function(){ /*Que l'on peut résumer par : $(function(){ */
				$('.caroussel').bxSlider({
					mode: "fade"
				});
			});
		</script>
	</body>
</html>