<form method="POST" action="index.php?page=article" class="notvisibleart article">
		<div class="fermer"> X </div>
		<p>Création d'un article</p>
		<label for="title">Titre :</label>
		<input id="title" name="titre" type="text" placeholder="Entrez votre titre">
		<label for="description">Description :</label>
		<textarea id="description" name="description" rows="4" cols="50" placeholder="Entrez votre description"></textarea>
		<label for="lien">Source :</label>
		<input id="lien" name="lien" type="text" placeholder="La source/lien">
		<input type="hidden" value="addarticle" name="action">
		<button type="submit">ENVOYER</button>
</form>