<div class="contactwrapper">
	<div class="col-md-12">
		<h2>Nous contacter</h2>
	</div>
	<div class="col-md-6 col-gauche">
		
		<p><i class="flaticon-telephone46"></i> Téléphone au 03 80 08 56 55</p>
		<p><i class="flaticon-black218"></i> Mail : DreamTeam@gmail.com</p>
		
		<div class="divlogo3wa col-md-offset-4 col-md-4">
			<img class="3wa" src="./views/images/logo3wa.png" alt="#">
			<p class="dream">Dream</p>
			<p class="team">Team</p>
		</div>
	</div>
	<div>	
		<form action="" method="post" class="col-md-6" >
			<div class="formcontact">
				<label><span class="labeltxt" >Email :</span><input class="inputstyle" type="text" name="email" placeholder="votre mail"></label>
			</div>
			<div class="formcontact">
				<label><span class="labeltxt">Nom et Prénom :</span><input class="inputstyle" type="text" name="nom" placeholder="votre nom et prénom"></label>
			</div >
			<div class="formcontact">
				<label><span class="labeltxt">Objet :</span><input class="inputstyle" type="text" name="objet" placeholder="votre objet"></label>
			</div>
			<div class="formcontact">
				<label><span class="labeltxt">Message :</span><textarea class="inputstyle" name="message" placeholder="votre message"></textarea></label>
			</div>
			<button type="envoyer" class="btn">Submit</button>	
		</form>
	</div>
<!-- 	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2639.219964896662!2d7.741729999999998!3d48.58648700000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796c84ed7c1b1d9%3A0xa3c93a25f60c1c4b!2sPlace+des+Halles!5e0!3m2!1sfr!2sfr!4v1431698508827" class="googlemap" ></iframe> -->
</div>

<style>

.contactwrapper
{
	position:relative;
}
.divlogo3wa
{
	margin-top: 50px;
}

.3wa
{
	display:inline-block;
	margin-left:40px;

}
.dream{
	font-size: 16px !important;
	text-transform: uppercase;
	font-weight: bold;
	padding: 0;
 	margin-top: 0;
    position:absolute;
    bottom:-22px;
    left:20px;
    color:white;
    transform:rotate(18deg);
}
.team
{
	font-weight: bold;
	font-size: 16px !important;
	text-transform: uppercase;
	color:white;
	position:absolute;
	bottom:-23px;
	left:82px;
	transform:rotate(-21deg);
}

.flati:before
{
	font-size:60px;
}
.col-gauche p
{
	margin-top:20px;
	font-size: 20px;
}
.inputstyle
{
	width:100%;
	display:inline-block;
}

.labeltxt{
	display: block;	
	vertical-align: top; 
	width: 100%;
}
.formcontact label
{
	margin: 20px 0 0 0;
	width: 100%;
}

.btn
{
	position:relative;
	top:-1px;
	background-color: #337ab7;
	color:white;
	margin-top:0px;
	width : 100%;
	margin: 0 auto 20px; 
	border-radius: 0 0 5px 5px;
	text-transform: uppercase;
}

</style>