<div class="contactwrapper">
	<h2>Nous contacter</h2>
	<div class="row">
		<div class="col-md-6 col-gauche">
			
			<p><i class="flaticon-telephone46"></i> Téléphone au 03 80 08 56 55</p>
			<p><i class="flaticon-black218"></i> Mail : DreamTeam@gmail.com</p>
			
			<div class="divlogo3wa col-md-offset-4 col-md-4">
				<img class="3wa" src="./views/images/logo3wa.png" alt="#">
				<p class="dream">Dream</p>
				<p class="team">Team</p>
			</div>
		</div>
		<div id="contact-content" class="col-md-6">	
			<form action="index.php?ajax=contact-form" method="POST" id="contact-form" >
				<div class="formcontact">
					<label><span class="labeltxt" >Email :</span><input id="contact-email" class="inputstyle" type="text" name="email" placeholder="votre mail"></label>
				</div>
				<div class="formcontact">
					<label><span class="labeltxt">Nom et Prénom :</span><input id="contact-nom" class="inputstyle" type="text" name="nom" placeholder="votre nom et prénom"></label>
				</div >
				<div class="formcontact">
					<label><span class="labeltxt">Objet :</span><input id="contact-objet" class="inputstyle" type="text" name="objet" placeholder="votre objet"></label>
				</div>
				<div class="formcontact">
					<label><span class="labeltxt">Message :</span><textarea id="contact-message" class="inputstyle" name="message" placeholder="votre message"></textarea></label>
				</div>
				<button type="envoyer" class="btn">Submit</button>	
			</form>
		</div>
	</div>
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2639.219964896662!2d7.741729999999998!3d48.58648700000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796c84ed7c1b1d9%3A0xa3c93a25f60c1c4b!2sPlace+des+Halles!5e0!3m2!1sfr!2sfr!4v1431698508827" class="googlemap" ></iframe>
</div>
