<form action="" method="POST">
			<div class="titrenewsujetforum">
				<input name="sujet" type="text" class="titresujet" placeholder="Sujet" required>
			</div>
			<div class="clearfix"></div>

			<div class="wrapper-mce clearfix">
				<textarea name="description" class="mce" ></textarea>
			</div>
			<input type="hidden" value="addSujet" name="action">
			<button class="" type="submit">CREER SUJET</button>
</form>