<div class="sujetforum">
	<a href="index.php?page=forum" class="returnForumSujet">Retourner au forum</a> 
	<div class="sujet">
	<div class="entete">
		<p class="col-md-2"><a href="index.php?page=profil-user&id_user=<?=$id_user?>"><?=$user_pseudo?></a></p>
		<p class="col-md-7"><?=$sujet?></p>
		<p class="col-md-3 dateSujet"><?=$date?></p>
	</div>
	<div class="textesujetforum">
			<?=$description?>
	</div>
	</div>
	<div class="commentaires">
		<?php require('apps/forum-commentaires.php') ?>
	</div>



 <?php if(isset($_SESSION['id']) && $_SESSION['id']>0) : ?>

	<button class="buttonReponseCommentaire" type="submit">Répondre</button>
	<div class="reponse-forum">
		<form action="index.php?page=forum-reponse" method="POST">
			<div class="clearfix"></div>
			<div class="wrapper-mce clearfix">
				<textarea name="description" class="mce" ></textarea>
			</div>
			<button class="repondre" type="submit">Répondre</button>
			<input type="hidden" value="<?= $id_sujet; ?>" name="id_forum">
			<input type="hidden" value="<?=$_SESSION['id'];?>" name="id_user">
		</form>
	</div>
<?php endif; ?>
</div>