<div class="content">
	<div class="forum ">
	<nav class="navforum">
		<?php require('./apps/forum-log.php') ;?>
		<span class="col-md-8">
		<input type="text" placeholder="Rechercher dans le forum">
		<select name="categorieSearch" id="categorieSearch">
          	 <option value="sujet">Sujet</option>
          	 <option value="auteur">Auteur</option>
      	 </select>
		<button id="search">Chercher</button>
		</span>
		<button class="actualiserforum col-md-2">Actualiser</button>
	</nav>
		<div class="entete">
			<p class="col-md-6">Sujet</p>
			<p class="col-md-2">Auteur</p>
			<p class="col-md-2">Nombre commentaires</p>
			<p class="col-md-2">Dernière réponse</p>
		</div>
		<?php require('apps/forum-liste.php'); ?>
	</div>
	<div class="newsujetforum">
		<button class="returnforum">Retourner sur le forum</button>
		
	</div>
</div>
<div>
</div>