<form method="POST" action="index.php?page=article" class="supprArticle notvisibleart">
		<div class="fermer"> X </div>
		<p>Suppression d'un article</p>
		<label for="title">Quel article voulez vous supprimez ?</label>
		<input id="title" name="titre" type="text" placeholder="Entrez votre titre">
		<input type="hidden" value="addarticle" name="action">
		<button type="submit">ENVOYER</button>
	</form>